### ISSUE TITLE
datePicker组件无法渲染selectTime 为 ‘’ 的情况

### ISSUE THREAD

**Issue by 4pmtong** [LLLLLamHo/zzc-design-mobile#19]
![image](https://user-images.githubusercontent.com/18047286/44964466-4fc90f80-af63-11e8-863d-23b273d9ff0a.png)
![image](https://user-images.githubusercontent.com/18047286/44964482-63747600-af63-11e8-882e-289dd3ff1533.png)

**Comment by LLLLLamHo** [comment]
fixed
