### ISSUE TITLE
datePicker

### ISSUE THREAD

**Issue by 4pmtong** [LLLLLamHo/zzc-design-mobile#2]

**Comment by 4pmtong** [comment]
*  props改变的时候，组件没有重新渲染
*  当minDate和maxDate相差太大的时候，选中年份位置出现明显位移
![image](https://user-images.githubusercontent.com/18047286/42272336-6a77c310-7fb8-11e8-83a4-b2b01e5170ce.png)
![image](https://user-images.githubusercontent.com/18047286/42272688-8a19ce88-7fb9-11e8-8d4a-09291ef13523.png)

**Comment by LLLLLamHo** [comment]
在1.2.2版本已经解决，并且有是因为better-scroll的版本冲突导致
