### ISSUE TITLE
时间控件例子里面的返回形参名字用一样的，便于复制直接使用

### ISSUE THREAD

**Issue by Huatingzi** [LLLLLamHo/zzc-design-mobile#3]
时间控件例子里面的返回形参名字用一样的，便于复制直接使用
![image](https://user-images.githubusercontent.com/20843521/42563766-9d56a322-8531-11e8-9476-0d9c29321f1c.png)

**Comment by LLLLLamHo** [comment]
会在1.3.5版本得到解决
