### ISSUE TITLE
建议DatePicker组件跨月选择日期时支持设置指定日期

### ISSUE THREAD

**Issue by beyondouyuan** [LLLLLamHo/zzc-design-mobile#30]
经测试代码如下：

     // DatePicker/util/date.js
    export function getFirstDate( year, month ): number {
        return new Date( new Date( `${year}/${resetDate( month + 1 )}/01` ).setDate( 1 ) ).getDate();
    }

     // DatePicker/components/DatePicker.js

    static defaultProps = {
          prefixCls: `${config.cls}-datepicker`,
          className: '',
          style: {},
          mode: 'date',
          lang: 'cn',
          minDate: '',
          maxDate: '',
          selectTime: null,
          minuteStep: 1,
          use12hour: false,
          visible: false,
          maskClose: true,
          touchEndExtra: false,  // 是否允许在跨月时设置指定日期时间
          touchEndExtraDate: {} // 指定的日期时间 touchEndExtraDate['day']...
    }
    
    touchEnd(scrollKey): void {
	const {
		onValueChange,
		mode,
		touchEndExtra,
		touchEndExtraDate
	} = this.props;

	let currDateData;
	let currDate;

	if (mode && mode.indexOf('date') != -1) {
		if (mode === 'datetime') {
			const currData = this.getCurrDate(scrollKey).currDate.split(' ');
			const data = currData[0].split('/');
			const time = currData[1].split(':');
			currDateData = data.concat(time);
		} else {
			currDateData = this.getCurrDate(scrollKey).currDate.split('/');
		}

		// 上一次选择的月份的日期在当前选中的月份的日期没有的时候，选中最后一个日期
		const currYear = parseInt(currDateData[0]);
		const currMonth = parseInt(currDateData[1]);
		const currDay = parseInt(currDateData[2]);
		const currHour = parseInt(currDateData[3]);
		const currMinute = parseInt(currDateData[4]);
		const currDateLastDay = getLastDate(currYear, currMonth);
		const currDateFirstDay = getFirstDate(currYear, currMonth);
		if (currDay > currDateLastDay) {
			/**
			 * 上一次选择的月份的日期在当前选中的月份的日期没有的时候，选中最后一个日期
			 * 增加touchEndExtra和touchEndExtraDate两个扩展属性
			 * 用于设置 当选择日期时候，上一次选择的月份日期是月末，当前日期切换到下一个月时后
			 * 选择设置为月初还是指定时间
			 * 如 2019/08/31 10:30切换到九月份时候
			 * 默认使用最后一个日期即 2018/09/30 00:00
			 * 若touchEndExtra为true且touchEndExtraDate['day']不存在时，
			 * 默认使用第一个日期即 2019/09/01 10:30
			 * 若touchEndExtra为true且分别传入有touchEndExtraDate['day'] touchEndExtraDate['hour'] touchEndExtraDate['minute']
			 * currDate即为传入的touchEndExtraDat对应值（仅支持设置 日 时 分）
			 */
			if (touchEndExtra) {
				const day = (isObject(touchEndExtraDate) && touchEndExtraDate['day']) ? touchEndExtraDate['day'] : currDateFirstDay;
				const hour = (isObject(touchEndExtraDate) && touchEndExtraDate['hour']) ? touchEndExtraDate['hour'] : currHour;
				const minute = (isObject(touchEndExtraDate) && touchEndExtraDate['minute']) ? touchEndExtraDate['minute'] : currMinute;
				currDate = new Date(`${currDateData[0]}/${currDateData[1]}/${day} ${hour}:${minute}`);
			} else {
				currDate = new Date(`${currDateData[0]}/${currDateData[1]}/${currDateLastDay}`);
			}
		} else {
			currDate = new Date(this.getCurrDate(scrollKey).currDate);
		}
	} else if (mode == 'time') {
		currDate = new Date(`1993/09/17 ${this.getCurrDate(scrollKey).currDate}`);
	} else if (mode == 'year') {
		currDate = new Date(`${this.getCurrDate(scrollKey).currDate}/09/17`);
	} else if (mode == 'month') {
		currDate = new Date(`1993/${this.getCurrDate(scrollKey).currDate}/17`);
	}
	this.initDate(currDate);
	if (onValueChange && isFunction(onValueChange)) {
		onValueChange(this.getCurrDate(scrollKey));
	}
    }

**Comment by LLLLLamHo** [comment]
已经为DataPicker添加了新的参数，具体可以看https://lllllamho.github.io/zzc-design-mobile/#change
