### ISSUE TITLE
3.0.4版本, Toast组件loading手动关闭bug

### ISSUE THREAD

**Issue by JunYanchan** [LLLLLamHo/zzc-design-mobile#33]
场景：请求接口需要用到Toast loading
预期：请求前调用Toast.loading()，不自动关闭，等待接口成功后，手动调用Toast.hideToast()关闭
实际： 调用Toast.hideToast()可以关闭，但是组件遮罩层仍然存在于body中
导致：点击页面其它元素无反应

**Comment by JunYanchan** [comment]
补充：是调用过快Toast.hideToast()才会造成，例如接口快速相应返回然后就调用的时候

**Comment by LLLLLamHo** [comment]
在3.0.8中解决问题
https://github.com/LLLLLamHo/zzc-design-mobile/pull/35
