### ISSUE TITLE
Form.Input 设置initialValue为false时失败了。

### ISSUE THREAD

**Issue by xieyihao** [LLLLLamHo/zzc-design-mobile#52]
给Input设置初始值为false时，设置失败了。

![image](https://user-images.githubusercontent.com/12508868/74017198-c1b24d80-49ce-11ea-815a-6929ff52c90c.png)

![image](https://user-images.githubusercontent.com/12508868/74017204-c5de6b00-49ce-11ea-877b-c7a5e68201a4.png)

**Comment by LLLLLamHo** [comment]
3.5.6将支持false转为字符串，initialValue在未null或者undefined时将会转为空字符串
