### ISSUE TITLE
Tabs Item可点击热区太小 会出现点不中情况

### ISSUE THREAD

**Issue by xieyihao** [LLLLLamHo/zzc-design-mobile#64]
现在有效点击区域仅为文案高度

![image](https://user-images.githubusercontent.com/12508868/82185196-6e2f9400-991b-11ea-877b-99e485ccd9fb.png)

期望有效点击区域占满整个Tabs Item.
![image](https://user-images.githubusercontent.com/12508868/82185283-94edca80-991b-11ea-8212-ef91e8565175.png)

**Comment by chunyangyang** [comment]
3.5.9修复
