### ISSUE TITLE
Feature:  From 表单 input输入框组件 配置项 增加 value  trim 功能

### ISSUE THREAD

**Issue by Lsmaxs** [LLLLLamHo/zzc-design-mobile#66]
## Steps to reproduce
1. 输入框输入常规值
2. 每个字符间隔加入空格
3. fromAllData ouput 出现空额

## What is expected?
增加配置项 可以trim当前输出值

## What is actually happening?
输入值后 用户特意隔开值间空隙

Environment | Info
-- | --
design | 3.6.0
React | 16.13.1
System | macos
Browser | chrome

**Comment by LLLLLamHo** [comment]
3.6.1解决
